In [1]:
import numpy as np

In [19]:
X_train = np.array([[ 1., -1.,  2.], [ 2.,  0.,  0.], [ 0.,  1., -1.]])
X_train

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [22]:
# [:,0] means row in column 0

x1 = (X_train[:,0]-X_train[:,0].mean())/X_train[:,0].std()
x2 = (X_train[:,1]-X_train[:,1].mean())/X_train[:,1].std()
x3 = (X_train[:,2]-X_train[:,2].mean())/X_train[:,2].std()

# (X_train-X_train.mean(axis=0))/X_train.std(axis=0)



In [24]:
(X_train-X_train.mean(axis=0))/X_train.std(axis=0)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [23]:
print(np.c_[x1,x2,x3])

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [26]:
from sklearn import preprocessing
import numpy as np
X_scaled = preprocessing.scale(X_train)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])